[#macro messageList param template=""]
	[#list wx.message.service.findMessages(param) as message]
		[#if template=""]
		[#nested message]
		[#else]
		[#include "/WEB-INF/t/tags/" + template + ".html"]
		[/#if]
	[/#list]
[/#macro]